### ISSUE TITLE
Pre-launch checklist

### ISSUE THREAD

**Issue by JohnPixle** [mauryaratan/analogwp-templates#489]
Summary of the changes required for the beta release:

- [x] Inline container padding should override preset
- [x] Neutralise variable slugs for spacing presets (padding 1, padding 2, padding 3 etc)
- [x] Neutralise variable slugs for shadow presets (shadow 1, shadow 2 etc)
- [x] Make shadow names editable, like padding presets if not too much of a trouble
- [x] Remove Elements gap preset from UI
- [x] Replace help links for container padding and shadows

- [x] Add PRO indicator in Shadows panel.
